apiVersion: v1
kind: Service
metadata:
  name: platform-node-port-srv
spec:
  type: NodePort
  selector:
    app: platform-service
  ports:
  - port: 80
    targetPort: 80
    name: platform-service
    protocol: TCP
