apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-service
spec:
  selector:
    matchLabels:
      app: platform-service
  
  template:
    metadata:
      labels:
        app: platform-service
    
    spec:
      containers:
      - name: platform-service
        image: ragibnoor19/platform.service
